---
- import_tasks: validate.yml
  run_once: true
  delegate_to: localhost

- name: Gather OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "os/{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
    - "os/{{ ansible_distribution | lower }}.yml"
    - "os/{{ ansible_os_family | lower }}.yml"
  when: firewall_provider == "auto"

- name: Define firewall_provider
  set_fact:
    firewall_provider: "{{ __firewall_provider }}"
  when: firewall_provider == "auto"

- include_tasks: "main-{{ firewall_provider }}.yml"
