---
- name: Converge
  hosts: all
  tasks:
    - name: "Set ansible_virtualization_type to docker"
      set_fact:
        ansible_virtualization_type: "docker"

    - name: "Include stonesoupkitchen.ufw"
      include_role:
        name: "stonesoupkitchen.ufw"
