# Install the firewall package.
---
- name: Define firewall_package
  set_fact:
    firewall_package: "{{ __firewall_package }}"
  when: firewall_package is not defined

- name: Install firewall package
  apt:
    name: "{{ firewall_package }}"
    state: "{{ firewall_package_state }}"
